export const technologies = [
    { name: 'JavaScript' },
    { name: 'TypeScript' },
    { name: 'Next.js' },
    { name: 'React' },
    { name: 'Node.js' },
    { name: 'Python' },
    { name: 'PHP' },
    { name: 'Flutter' },
    { name: 'PostgreSQL' },
    { name: 'MySQL' },
    { name: 'MongoDB' },
    { name: 'Supabase' },
    { name: 'Prisma' },
    { name: 'Tailwind CSS' },
    { name: 'Git' },
    { name: 'Cloudflare' },
];
