import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { remark } from 'remark';
import remarkGfm from 'remark-gfm';
import remarkHtml from 'remark-html';

const postsDirectory = path.join(process.cwd(), 'posts');
const outPath = path.join(process.cwd(), 'lib', 'posts-data.js');

const files = fs.readdirSync(postsDirectory).filter((filename) => filename.endsWith('.md'));

const posts = await Promise.all(
    files.map(async (filename) => {
        const slug = filename.replace(/\.md$/, '');
        const fileContents = fs.readFileSync(path.join(postsDirectory, filename), 'utf8');
        const { data, content } = matter(fileContents);
        const processed = await remark().use(remarkGfm).use(remarkHtml).process(content);
        return { slug, frontmatter: data, contentHtml: processed.toString() };
    })
);

const banner = '// Auto-generated by scripts/build-posts.mjs from posts/*.md. Do not edit directly.\n';
fs.writeFileSync(outPath, `${banner}export const postsData = ${JSON.stringify(posts, null, 4)};\n`);

console.log(`Generated ${outPath} with ${posts.length} posts`);
